// Autogenerated by github.com/snonky/pocketbase-gogen.
// Please feel free to edit after noting the explanation:
//
// This file is an intermediate product of the proxy generation.
// It is called a 'schema as code' or just 'template'. It is not meant to be
// compiled it is only meant for human interaction, place it in a separate package
// but never import it.
// Here's what you can do to influence the final code generation step:
//
// Do:
//   - Edit the struct names. The names are directly copied to the proxy struct definitions.
//   - Remove structs or fields that you don't want in the generated code. Note that upon removing a struct
//     you also have to remove any fields that have that struct as their type.
//   - Edit the type name in the '// select:' comments.
//   - Change the const names of the select options by adding alias lines (// >) to the select options list.
//     Example:
//     // select: MySelectType
//     // - optionA
//     // > aliasA
//     // - v2.0
//     // > v2_0
//   - Edit the field names. If you do, the generator still needs to know the original database field name.
//     To provide this, add a '// schema-name: [original field name]' comment directly above the field.
//   - Add methods to the template structs. The generator will replace any fields you access with the also
//     generated getters/setters. Be aware of that when repeatedly assigning a template field. You are
//     calling a setter on every assignment. The methods can also call each other.
//
// Do not:
//   - Add structs that do not represent a PB collection.
//   - Add fields that are not part of the PB schema to the structs.
//   - Change the '// collection-name:' comments unless the collection was actually renamed.
//     If the comment is missing from the first struct field, the generator will print a warning.
//   - Change the select values in the () of the '// select:' comments'
//   - Remove the '// system:' doc comments from the system fields. Generation will fail if you do so.
//   - Shadow any names from the core.Record struct. Generation will also fail for safety.
//   - Rename fields without preserving the original name with a '// schema-name:' comment.'
//
// If you edit this file, be careful and back it up to prevent the changes from being overridden by
// subsequent runs of the template command. Check out the PocketBase docs to find out how to use the
// generated code in your code: https://pocketbase.io/docs/go-record-proxy/
package pbschema

import "github.com/pocketbase/pocketbase/tools/types"

type Users struct {
	// collection-name: users
	// system: id
	Id string
	// system: password
	password string
	// system: tokenKey
	tokenKey string
	// system: email
	email string
	// system: emailVisibility
	emailVisibility bool
	// system: verified
	verified bool
	name     string
	avatar   string
	created  types.DateTime
	updated  types.DateTime
}

type Uploads struct {
	// collection-name: uploads
	// system: id
	Id    string
	title string
	// select: TypeSelectType
	// - book
	// - article
	// - podcast
	// - lecture
	// - youtube
	// - essay
	// - summary
	type_ int
	file  string
	user  *Users
	// select: StatusSelectType
	// - PENDING
	// - PROCESSING
	// - FAILED
	// - SUCCESS
	status      int
	people      []*People
	tags        []*Tags
	topic       []*Topics
	num_pages   float64
	publication *Publications
	uploads     []*Uploads
	created     types.DateTime
	updated     types.DateTime
}

type People struct {
	// collection-name: people
	// system: id
	Id     string
	name   string
	source string
	// select: TypeSelectType
	// - youtube_channel
	// - author
	// - publication
	// - podcast
	type_   int
	user    *Users
	created types.DateTime
	updated types.DateTime
}

type Tags struct {
	// collection-name: tags
	// system: id
	Id      string
	title   string
	user    *Users
	created types.DateTime
	updated types.DateTime
}

type Nodes struct {
	// collection-name: nodes
	// system: id
	Id string
	// select: TypeSelectType
	// - author
	// - tag
	// - topic
	// - upload
	// - highlight
	// - bookmark
	// - note
	type_     int
	record_id string
	user      *Users
	label     string
	data      string
	created   types.DateTime
	updated   types.DateTime
}

type Topics struct {
	// collection-name: topics
	// system: id
	Id      string
	title   string
	user    *Users
	created types.DateTime
	updated types.DateTime
}

type Edges struct {
	// collection-name: edges
	// system: id
	Id     string
	source *Nodes
	target *Nodes
	user   *Users
	// select: TypeSelectType
	// - authored_by
	// - tagged_with
	// - belongs_to
	// - highlight_of
	// - bookmark_of
	// - note_of
	// - published_by
	// - about_person
	// - links_to
	// - summary_of
	type_   int
	created types.DateTime
	updated types.DateTime
}

type Pages struct {
	// collection-name: pages
	// system: id
	Id       string
	markdown string
	upload   *Uploads
	page     float64
	user     *Users
	created  types.DateTime
	updated  types.DateTime
}

type Highlights struct {
	// collection-name: highlights
	// system: id
	Id string
	// select: ColorSelectType
	// - yellow
	// - green
	// - blue
	// - pink
	// - purple
	color        int
	text         string
	comment      string
	start_offset float64
	end_offset   float64
	page         *Pages
	upload       *Uploads
	user         *Users
	tags         []*Tags
	created      types.DateTime
	updated      types.DateTime
}

type Bookmarks struct {
	// collection-name: bookmarks
	// system: id
	Id          string
	comment     string
	page_number float64
	block_id    string
	page        *Pages
	upload      *Uploads
	user        *Users
	tags        []*Tags
	created     types.DateTime
	updated     types.DateTime
}

type Notes struct {
	// collection-name: notes
	// system: id
	Id          string
	content     string
	page        *Pages
	page_number float64
	block_id    string
	upload      *Uploads
	tags        []*Tags
	user        *Users
	created     types.DateTime
	updated     types.DateTime
}

type WritingProjects struct {
	// collection-name: writing_projects
	// system: id
	Id      string
	title   string
	content string
	// select: StatusSelectType
	// - draft
	// - published
	// - archived
	status     int
	tags       []*Tags
	topics     []*Topics
	uploads    []*Uploads
	highlights []*Highlights
	bookmarks  []*Bookmarks
	notes      []*Notes
	user       *Users
	created    types.DateTime
	updated    types.DateTime
}

type Publications struct {
	// collection-name: publications
	// system: id
	Id   string
	name string
	url  string
	// select: TypeSelectType
	// - podcast
	// - youtube_channel
	// - blog
	// - other
	type_   int
	user    *Users
	created types.DateTime
	updated types.DateTime
}

type Chats struct {
	// collection-name: chats
	// system: id
	Id    string
	user  *Users
	title string
	// select: TypeSelectType
	// - search
	// - chat
	type_   int
	created types.DateTime
	updated types.DateTime
}

type Messages struct {
	// collection-name: messages
	// system: id
	Id   string
	chat *Chats
	// select: RoleSelectType
	// - user
	// - assistant
	role    int
	content string
	sources string
	user    *Users
	created types.DateTime
	updated types.DateTime
}

type Collections struct {
	// collection-name: collections
	// system: id
	Id          string
	name        string
	description string
	user        *Users
	uploads     []*Uploads
	created     types.DateTime
	updated     types.DateTime
}

type DocumentChunks struct {
	// collection-name: document_chunks
	// system: id
	Id          string
	upload      *Uploads
	page        *Pages
	page_number float64
	chunk_index float64
	content     string
	user        *Users
	vector_id   float64
	created     types.DateTime
	updated     types.DateTime
}

type Preferences struct {
	// collection-name: preferences
	// system: id
	Id               string
	reader_settings  string
	workspace_layout string
	ui_settings      string
	user             *Users
	created          types.DateTime
	updated          types.DateTime
}

type ReadingProgress struct {
	// collection-name: reading_progress
	// system: id
	Id              string
	user            *Users
	upload          *Uploads
	current_page    float64
	scroll_position float64
	created         types.DateTime
	updated         types.DateTime
}

type ProcessingJobs struct {
	// collection-name: processing_jobs
	// system: id
	Id string
	// select: JobTypeSelectType
	// - upload.parse_or_transcribe
	// - chunk.generate
	// - page.summarize
	// - chunk.embed
	// - chunk.embed.submit
	// - chunk.embed.poll
	job_type int
	// select: StatusSelectType
	// - queued
	// - running
	// - succeeded
	// - failed
	// - deadletter
	// - cancelled
	status              int
	priority            float64
	attempts            float64
	max_attempts        float64
	scheduled_at        types.DateTime
	lease_until         types.DateTime
	started_at          types.DateTime
	finished_at         types.DateTime
	dedupe_key          string
	payload_json        string
	error_code          string
	error_message       string
	worker_id           string
	trace_id            string
	user                *Users
	upload              *Uploads
	page                *Pages
	chunk               *DocumentChunks
	embedding_operation *EmbeddingOperations
	created             types.DateTime
	updated             types.DateTime
}

type ProcessingJobEvents struct {
	// collection-name: processing_job_events
	// system: id
	Id         string
	job        *ProcessingJobs
	event_type string
	message    string
	meta_json  string
	created    types.DateTime
	updated    types.DateTime
}

type Summaries struct {
	// collection-name: summaries
	// system: id
	Id             string
	user           *Users
	source_upload  *Uploads
	source_page    *Pages
	summary_upload *Uploads
	summary_page   *Pages
	// select: StatusSelectType
	// - processing
	// - success
	// - failed
	status int
	error  string
	// select: ScopeSelectType
	// - page
	scope   int
	created types.DateTime
	updated types.DateTime
}

type EmbeddingOperations struct {
	// collection-name: embedding_operations
	// system: id
	Id                    string
	upload                *Uploads
	processing_job        *ProcessingJobs
	page                  *Pages
	user                  *Users
	provider              string
	provider_operation_id string
	// select: StatusSelectType
	// - queued
	// - submitted
	// - polling
	// - succeeded
	// - failing
	// - cancelled
	// - expired
	status           int
	model            string
	chunk_ids_json   string
	total_chunks     float64
	succeeded_chunks float64
	failed_chunks    float64
	attempts         float64
	max_attempts     float64
	next_poll_at     types.DateTime
	lease_until      types.DateTime
	worker_id        string
	error_message    string
	submitted_at     types.DateTime
	last_polled_at   types.DateTime
	finished_at      types.DateTime
	created          types.DateTime
	updated          types.DateTime
}
