/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppUploadIndexRouteImport } from './routes/_app/upload/index'
import { Route as AppReaderIndexRouteImport } from './routes/_app/reader/index'
import { Route as AppGraphIndexRouteImport } from './routes/_app/graph/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app/documents/index'

const SigninLazyRouteImport = createFileRoute('/signin')()

const SigninLazyRoute = SigninLazyRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadIndexRoute = AppUploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => AppRoute,
} as any)
const AppReaderIndexRoute = AppReaderIndexRouteImport.update({
  id: '/reader/',
  path: '/reader/',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphIndexRoute = AppGraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/documents/': typeof AppDocumentsIndexRoute
  '/graph/': typeof AppGraphIndexRoute
  '/reader/': typeof AppReaderIndexRoute
  '/upload/': typeof AppUploadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/graph': typeof AppGraphIndexRoute
  '/reader': typeof AppReaderIndexRoute
  '/upload': typeof AppUploadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/graph/': typeof AppGraphIndexRoute
  '/_app/reader/': typeof AppReaderIndexRoute
  '/_app/upload/': typeof AppUploadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/documents/'
    | '/graph/'
    | '/reader/'
    | '/upload/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/documents' | '/graph' | '/reader' | '/upload'
  id:
    | '__root__'
    | '/_app'
    | '/signin'
    | '/_app/documents/'
    | '/_app/graph/'
    | '/_app/reader/'
    | '/_app/upload/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SigninLazyRoute: typeof SigninLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upload/': {
      id: '/_app/upload/'
      path: '/upload'
      fullPath: '/upload/'
      preLoaderRoute: typeof AppUploadIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reader/': {
      id: '/_app/reader/'
      path: '/reader'
      fullPath: '/reader/'
      preLoaderRoute: typeof AppReaderIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/graph/': {
      id: '/_app/graph/'
      path: '/graph'
      fullPath: '/graph/'
      preLoaderRoute: typeof AppGraphIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppGraphIndexRoute: typeof AppGraphIndexRoute
  AppReaderIndexRoute: typeof AppReaderIndexRoute
  AppUploadIndexRoute: typeof AppUploadIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppGraphIndexRoute: AppGraphIndexRoute,
  AppReaderIndexRoute: AppReaderIndexRoute,
  AppUploadIndexRoute: AppUploadIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SigninLazyRoute: SigninLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
