/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceIndexRouteImport } from './routes/_app/workspace/index'
import { Route as AppUploadIndexRouteImport } from './routes/_app/upload/index'
import { Route as AppLibraryIndexRouteImport } from './routes/_app/library/index'
import { Route as AppGraphIndexRouteImport } from './routes/_app/graph/index'
import { Route as AppChatIndexRouteImport } from './routes/_app/chat/index'

const SigninLazyRouteImport = createFileRoute('/signin')()

const SigninLazyRoute = SigninLazyRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceIndexRoute = AppWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadIndexRoute = AppUploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryIndexRoute = AppLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphIndexRoute = AppGraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninLazyRoute
  '/chat/': typeof AppChatIndexRoute
  '/graph/': typeof AppGraphIndexRoute
  '/library/': typeof AppLibraryIndexRoute
  '/upload/': typeof AppUploadIndexRoute
  '/workspace/': typeof AppWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninLazyRoute
  '/chat': typeof AppChatIndexRoute
  '/graph': typeof AppGraphIndexRoute
  '/library': typeof AppLibraryIndexRoute
  '/upload': typeof AppUploadIndexRoute
  '/workspace': typeof AppWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/graph/': typeof AppGraphIndexRoute
  '/_app/library/': typeof AppLibraryIndexRoute
  '/_app/upload/': typeof AppUploadIndexRoute
  '/_app/workspace/': typeof AppWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/chat/'
    | '/graph/'
    | '/library/'
    | '/upload/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/chat'
    | '/graph'
    | '/library'
    | '/upload'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/signin'
    | '/_app/chat/'
    | '/_app/graph/'
    | '/_app/library/'
    | '/_app/upload/'
    | '/_app/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SigninLazyRoute: typeof SigninLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace/': {
      id: '/_app/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AppWorkspaceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload/': {
      id: '/_app/upload/'
      path: '/upload'
      fullPath: '/upload/'
      preLoaderRoute: typeof AppUploadIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/': {
      id: '/_app/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AppLibraryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/graph/': {
      id: '/_app/graph/'
      path: '/graph'
      fullPath: '/graph/'
      preLoaderRoute: typeof AppGraphIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppGraphIndexRoute: typeof AppGraphIndexRoute
  AppLibraryIndexRoute: typeof AppLibraryIndexRoute
  AppUploadIndexRoute: typeof AppUploadIndexRoute
  AppWorkspaceIndexRoute: typeof AppWorkspaceIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatIndexRoute: AppChatIndexRoute,
  AppGraphIndexRoute: AppGraphIndexRoute,
  AppLibraryIndexRoute: AppLibraryIndexRoute,
  AppUploadIndexRoute: AppUploadIndexRoute,
  AppWorkspaceIndexRoute: AppWorkspaceIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SigninLazyRoute: SigninLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
