package collections

const (
	Users          = "users"
	Uploads        = "uploads"
	Pages          = "pages"
	People         = "people"
	Publications   = "publications"
	Tags           = "tags"
	Topics         = "topics"
	Highlights     = "highlights"
	Bookmarks      = "bookmarks"
	Nodes          = "nodes"
	Edges          = "edges"
	Notes          = "notes"
	Summaries      = "summaries"
	ChatContexts   = "chat_contexts"
	DocumentChunks = "document_chunks"
	EmbeddingJobs  = "embedding_jobs"
	Queue          = "queue"
	Collections    = "collections"
	Chats          = "chats"
	Messages       = "messages"
	DocumentChunksEmbeddings = "document_chunks_embeddings"
)
